# Generated by Django 4.2.7 on 2026-05-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprunt',
            old_name='notes',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='utilisateur_email',
            field=models.CharField(null=True),
        ),
    ]
