# Generated by Django 4.2.7 on 2026-05-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_notes_emprunt_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourEmprunt',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
