stages:
  preprocess:
    cmd: python scripts/preprocess.py data/loans.csv data/loans_clean.csv
    deps:
      - scripts/preprocess.py
      - data/loans.csv
    params:
      - params.yaml:
          - data
    outs:
      - data/loans_clean.csv

  train:
    cmd: python scripts/train.py data/loans_clean.csv model/model.pkl
    deps:
      - scripts/train.py
      - data/loans_clean.csv
    params:
      - params.yaml:
          - svd
    outs:
      - model/model.pkl

  evaluate:
    cmd: python scripts/evaluate.py model/model.pkl data/loans_clean.csv metrics/metrics.json
    deps:
      - scripts/evaluate.py
      - model/model.pkl
      - data/loans_clean.csv
    params:
      - params.yaml:
          - data
          - svd
    metrics:
      - metrics/metrics.json:
          cache: false
