# Generated by Django 4.2.7 on 2026-05-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('utilisateur_id', models.CharField(
                    db_index=True, max_length=255)),
                ('livre_id', models.CharField(db_index=True, max_length=255)),
                ('utilisateur_nom', models.CharField(blank=True, max_length=200)),
                ('utilisateur_carte', models.CharField(blank=True, max_length=20)),
                ('livre_titre', models.CharField(blank=True, max_length=255)),
                ('livre_isbn', models.CharField(blank=True, max_length=13)),
                ('livre_auteur', models.CharField(blank=True, max_length=255)),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='pending', max_length=20)),
                ('jours_retard', models.PositiveIntegerField(default=0)),
                ('penalite_fcfa', models.DecimalField(
                    decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
