# Generated by Django 4.2.7 on 2026-05-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_retouremprunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='before_notification_is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='retard_notification_is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
