# Generated by Django 4.2.7 on 2026-05-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_emprunt_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
